POST http://localhost:3333/todo
Content-Type: application/json

{
    "description": "Item 01",
    "checked": false
}

###

GET http://localhost:3333/todo

###

GET http://localhost:3333/todo?id=be5721fc-98a2-45df-8e01-de4bb63ffcef

###

PUT http://localhost:3333/todo/be5721fc-98a2-45df-8e01-de4bb63ffcef
Content-Type: application/json

{
    "description": "Item 02",
    "checked": true
}

###

DELETE http://localhost:3333/todo/a222adbd-5e8b-414f-987a-cc4c26886155